name: skribla
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_remote_config: ^5.0.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.3
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  in_app_review: ^2.0.9
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.1
  path_provider: ^2.1.4
  phosphor_flutter: ^2.1.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
